### ISSUE TITLE
Uwsgi and new agama.ini file

### ISSUE THREAD

**Issue by MrLightWood** [romankuchin/ica0002-2020#27]
Hello! I was doing lab 4 and encountered a problem in task 8. When changing agama.ini file with a new MySQL configuration instead of sqlite3, my server does not render the web page. http://193.40.156.86:3580/
The problem started after changing agama.ini file in /etc/uwsgi/apps-enabled/
If I change agama file to the previous one with sqlite3 configuration, then everything works well.
I installed python3-pymysql on my app server, so it should work.
I guess uwsgi cannot connect to the MySQL server, which is another host. 
my agama.ini file looks like that:
![image](https://user-images.githubusercontent.com/17985968/94308405-2979d080-ff7f-11ea-9954-f66eecf2ef00.png)

**Comment by MrLightWood** [comment]
That's how my mysql task file looks like:
![image](https://user-images.githubusercontent.com/17985968/94308528-55955180-ff7f-11ea-8468-70960e31c295.png)

**Comment by hudolejev** [comment]
Hello.

uWSGI part is configured correctly.

>  I guess uwsgi cannot connect to the MySQL server, which is another host.

This guess is correct. You can verify it by running this from the uWSGI host:

```
telnet <mysql-server-ip> 3306
```

You'll probably get 'connection refused' which indicates that MySQL is not answering from that host.

You can check the reason by running this command on MySQL host:

```
netstat -lnpt
```

You will notice that MySQL is listening on local interface, so it's not accessible from outside.

The problem is in `Add conf lines` task. Please check the result on the managed host, you'll notice it at once (:

I recommend not to use `blockinfile` and `lineinfile`, and use `copy` or `template` instead.

**Comment by MrLightWood** [comment]
Thanks for your help. Everything works perfectly now :D 👍
