### ISSUE TITLE
Discord Link + Lab 10 Task 1

### ISSUE THREAD

**Issue by 6monlambert** [romankuchin/ica0002-2020#51]
Hello,

Is it possible to have a new link to join the Discord server please ? The one on the main page is not valid anymore.

Moreover, I'm facing an issue with the backup user connexion to the database.
I created the user, with his home repo in which I put the .my.cnf, in which I specified : 

```
[client]
user=backup
password=[clear password of the user]

[mysqldump]
no_tablespaces
```

If I check in my database, I have the user with all accesses on localhost : 

![image](https://user-images.githubusercontent.com/32525162/99087326-4fad0b80-25d3-11eb-9da7-341a7dcdbd5c.png)

Still, I can't connect without specifying the -p option for the mysqldump, and therefore putting the password by hand : 

![image](https://user-images.githubusercontent.com/32525162/99087552-93077a00-25d3-11eb-9840-41a43dea746e.png)

It does not work either if I do a sudo to run the command with the backup user.
Do you have any idea/leads ?

Thanks a lot

**Comment by romankuchin** [comment]
It looks that "using password: NO" is the issue. Seems that user backup should use password for authentication. 
If you switch to user "backup" can you read .my.cnf?

New Discord link: https://discord.gg/twjBSAdm

**Comment by 6monlambert** [comment]
Hello,

Thank you for your answer.

Unfortunately, I can't directly switch to user backup : 

![image](https://user-images.githubusercontent.com/32525162/99091837-15df0380-25d9-11eb-8546-d0e534168d7a.png)

Otherwise, if I try to read the ~/.my.cnf file of backup with a sudo it works : 

![image](https://user-images.githubusercontent.com/32525162/99091956-3909b300-25d9-11eb-8494-ed9d45c2cf10.png)

The thing is, when I run the mysql command  just with a sudo, it considers that the user ubuntu runs it : 

![image](https://user-images.githubusercontent.com/32525162/99092090-622a4380-25d9-11eb-9df8-3428498d9992.png)

**Comment by romankuchin** [comment]
As per your output it doesn't use .my.cnf.

That's why:
# sudo -u backup cat ~/.my.cnf
cat: /root/.my.cnf: Permission denied

So, to test this command you have to switch to user backup properly. With sudo it looks for .my.cnf in wrong place.

**Comment by hudolejev** [comment]
> "using password: NO"

This is the root cause indeed. There are three problems here that need to be fixed.

1.

First, from your screenshots it seems that you are are running the `mysqldump` command without providing a password. You need `-p` parameter to invoke the password prompt. Please check task description, it has the exactly same problem description, and the correct command to use: https://github.com/romankuchin/ica0002-2020/blob/master/10-backups/lab.md#mysql-dump

2.

Second, when invoking `sudo` you are not getting the user profile loaded, as Sudo does not invoke the login shell. As Roman pointed out before you are still operating with root's profile, that's why `~/.my.cnf` gets resolved to `/root/.my.cnf`.

If the first problem is solved (`mysqldump -p` works) and you now want to test non-interactive login with using `~/.my.cnf` you will indeed need to switch to user `backup` (using `su`, not `sudo`):

```
su - backup
```

3.

And here comes the third problem.

> This account is currently not available

It means that there is no usable login shell set for user `backup`, so you cannot change to that. You can find the reason in the `/etc/passwd` file (shell is the last column).

You can change the login shell for user with Ansible module [user](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#parameter-shell). `/bin/sh` or `/bin/bash` would work.

After that `su - backup` should work, and you can also solve the problem 2 easily.

**Comment by 6monlambert** [comment]
Hello,
Sorry for the delay in my answer. The problem is now fixed.

Thanks a lot
